### ISSUE TITLE
Violet Plugins cannot be used

### ISSUE THREAD

**Issue by 475813283** [AppIeWorm/Violet#5]
![image](https://user-images.githubusercontent.com/80757284/197502672-cfff74ca-18e0-4813-abc6-dce1d932b4e2.jpeg)

**Comment by MatoiDev** [comment]
The thing is you have Alexa's [Violet](https://github.com/Traurige/Violet/blob/29c86af9cd8abb84ff74be0c1e62f8d500895bc1/Preferences/entry.plist#L8) installed. There is a conflict due to equal preference bundle IDs. I will fix that in the next release.

**Comment by 475813283** [comment]
How much is the latest version? I wish I could use this plug-in

**Comment by MatoiDev** [comment]
All versions of this tweak are completely free.  I will not take money from you for it, now a new version of the tweak with support for ios 13 is being tested, in which I will fix the conflict with Alexa's Violet.
