### ISSUE TITLE
Custom image Gifs do not work

### ISSUE THREAD

**Issue by Supernova1114** [AppIeWorm/Violet#6]
Normal images work, but choosing a gif will just show up as one frame.

Default maid gif works.

Tested gifs with and without alpha.

iOS 14.8
iPhone XR 
Have tried respring, does not make it work.
https://streamable.com/oe6u8s

**Comment by Supernova1114** [comment]
By the way, thank you for releasing this, I have been looking for a replacement ever since the original violet went down. :)

**Comment by MatoiDev** [comment]
Thx a lot for your feedback!  I didn't add a feature to set GIFs because I'm afraid to kill your phone:D  The default maid "gif" is just a game with threads. btw it's a good idea, so thanks for the motivation, I'll try to implement it in one of the next versions!
